### ISSUE TITLE
Check should also work with `inherits`

### ISSUE THREAD

**Issue by alexjfisher** [voxpupuli/puppet-lint-absolute_classname-check#20]

**Comment by bodgit** [comment]
It also doesn't seem to detect references such as `Class['::foo::bar']` which would be handy.

**Comment by ekohl** [comment]
> It also doesn't seem to detect references such as `Class['::foo::bar']` which would be handy.

Fair point, but deserves its own issue.

**Comment by alexjfisher** [comment]
> > It also doesn't seem to detect references such as `Class['::foo::bar']` which would be handy.
> 
> Fair point, but deserves its own issue.

I *might* even have a go at fixing it.
