### ISSUE TITLE
Matching resources other than classes in 0.2.x

### ISSUE THREAD

**Issue by edestecd** [voxpupuli/puppet-lint-absolute_classname-check#6]
After updating to 0.2.x we now get false positives on References.
For example this now fails complaining about the require statement:

```
file { '/path'
  ensure => present,
  require => Shellvar['http_proxy'],
}
```

I cannot reconcile what commit did this, but the only major change seems to be this:
https://github.com/voxpupuli/puppet-lint-absolute_classname-check/commit/47c47f08a3f81b738f4db1d4ddbe384aa566fc51

**Comment by edestecd** [comment]
OK after reviewing the commit it makes sense to me now.

The intention was to check this:
`require class_name`

But we are also unintentionally checking the Metaparameter require like above.

**Comment by claytono** [comment]
I'm also running into the same issue.  I'm getting problems with resources like:

```
    exec { 'set-power-policy':
      command => "ipmitool chassis policy ${power_policy}",
      unless  => "timeout -k 60 30 ipmitool chassis policy list | grep -q ${power_policy}",
      require => [Package['ipmitool'], Kmod::Load[$ipmi_modules]],
      timeout => 30,
      returns => [ '0', '1' ],
    }
```

In this case it thinks Package['ipmitool'] should be Package['::ipmitool']

**Comment by EmilienM** [comment]
Running in same issue everywhere in OpenStack, this is a total disaster.
http://logs.openstack.org/27/332227/1/check/gate-puppet-openstacklib-puppet-lint/9112794/console.html#_2016-06-22_21_33_59_027038

with this resource: https://github.com/openstack/puppet-openstacklib/blob/master/manifests/db/mysql.pp#L57

We pinned the gem for now, until a solution is found (btw, we have ~30 Puppet modules to fix if there is a solution).

**Comment by rnelson0** [comment]
@liamjbennett Any ideas on how to more accurately restrict your original change to the directives rather than metaparameters?

**Comment by nibalizer** [comment]
Hey this is me too

**Comment by domcleal** [comment]
I've opened #7 with a fix.
